version: '3.8'

services:
  server:
    image: server
    build:
      context: .
      target: final
    ports:
      - "5092:5092"
      - "8080:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORTS: 8080
      ASPNETCORE_Kestrel__Certificates__Default__Password: "123456"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      IN_DOCKER: "true"
    volumes:
      - .aspnet/https:/https/
